version: 2.1
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            pull_request:
              types:
                - approved
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Build
          command: npm install && npm run build
