version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only: /.*/
          pull_request:
            types:
              - approved
