version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: env && echo "this is the build job"
workflows:
  build-and-test:
    jobs:
      - build:
        filters:
          pull_request_review:
            types: [submitted]
